import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { map } from 'rxjs/operators';
import { environment } from 'src/environments/environment';
import { isDemoMode } from '../demo/demo-mode';

/** Día de un microciclo (fila por jornada entre startDate y endDate). */
export interface MicrocycleDay {
  microcycleDayId: number;
  microcycleId: number;
  dayDate: string;
  dayType: 'training' | 'rest' | 'match' | string;
  mdLabel: string | null;
  mdLabel2: string | null;
  trainingSessionId: number | null;
  notes: string | null;
}

/** Microciclo (Mon-Sun aprox., termina el día del partido). */
export interface Microcycle {
  microcycleId: number;
  teamId: number;
  clubId: number;
  name: string;
  matchDate: string;
  matchPreparationId: number | null;
  startDate: string;
  endDate: string;
  restDay: string | null;
  autoGenerated: boolean;
  createdByName: string | null;
  matchType?: string | null;
  matchVenue?: string | null;
  days?: MicrocycleDay[];
}

/** Payload mínimo para crear un microciclo manualmente. */
export interface MicrocycleCreatePayload {
  teamId: number;
  clubId: number;
  name: string;
  matchDate: string;
  startDate: string;
  endDate: string;
  restDay?: string | null;
  matchPreparationId?: number | null;
  createdByUserId?: number | null;
  createdByName?: string | null;
  days?: Array<Partial<MicrocycleDay> & { dayDate: string }>;
}

export interface MicrocycleUpdatePayload {
  name?: string;
  matchDate?: string;
  startDate?: string;
  endDate?: string;
  restDay?: string | null;
  matchPreparationId?: number | null;
}

export interface MicrocycleDayUpdatePayload {
  dayType?: string;
  mdLabel?: string | null;
  mdLabel2?: string | null;
  notes?: string | null;
  trainingSessionId?: number | null;
}

/**
 * Cliente Angular del módulo de Microciclos del Modo Profesional
 * (endpoint {@code /rest/microcycle}).
 *
 * <p>En modo demo devuelve un microciclo de la semana actual.</p>
 */
@Injectable({ providedIn: 'root' })
export class MicrocycleService {

  private readonly baseUrl = `${environment.apiUrl}microcycle`;

  constructor(private http: HttpClient) {}

  listByTeam(teamId: number): Observable<Microcycle[]> {
    if (isDemoMode()) return of([this.demoMicrocycle(teamId)]);
    return this.http
      .get<any>(`${this.baseUrl}/team/${teamId}`)
      .pipe(map(resp => Array.isArray(resp?.data) ? resp.data : []));
  }

  getCurrent(teamId: number): Observable<Microcycle | null> {
    if (isDemoMode()) return of(this.demoMicrocycle(teamId));
    return this.http
      .get<any>(`${this.baseUrl}/team/${teamId}/current`)
      .pipe(map(resp => (resp?.data ?? null) as Microcycle | null));
  }

  listUpcoming(teamId: number): Observable<Microcycle[]> {
    if (isDemoMode()) return of([this.demoMicrocycle(teamId)]);
    return this.http
      .get<any>(`${this.baseUrl}/team/${teamId}/upcoming`)
      .pipe(map(resp => Array.isArray(resp?.data) ? resp.data : []));
  }

  getById(microcycleId: number): Observable<Microcycle> {
    if (isDemoMode()) return of(this.demoMicrocycle(9001));
    return this.http
      .get<any>(`${this.baseUrl}/${microcycleId}`)
      .pipe(map(resp => resp?.data as Microcycle));
  }

  create(payload: MicrocycleCreatePayload): Observable<Microcycle> {
    if (isDemoMode()) return of({ ...this.demoMicrocycle(payload.teamId), microcycleId: Date.now(), name: payload.name });
    return this.http
      .post<any>(`${this.baseUrl}/`, payload)
      .pipe(map(resp => resp?.data as Microcycle));
  }

  update(microcycleId: number, payload: MicrocycleUpdatePayload): Observable<Microcycle> {
    if (isDemoMode()) return of({ ...this.demoMicrocycle(9001), microcycleId, ...payload });
    return this.http
      .put<any>(`${this.baseUrl}/${microcycleId}`, payload)
      .pipe(map(resp => resp?.data as Microcycle));
  }

  delete(microcycleId: number): Observable<boolean> {
    if (isDemoMode()) return of(true);
    return this.http
      .delete<any>(`${this.baseUrl}/${microcycleId}`)
      .pipe(map(resp => !!resp?.data));
  }

  autoGenerateFromMatches(
    teamId: number,
    clubId: number,
    createdByUserId?: number | null,
    createdByName?: string | null
  ): Observable<Microcycle[]> {
    if (isDemoMode()) return of([this.demoMicrocycle(teamId)]);
    const body: any = { clubId };
    if (createdByUserId != null) body.createdByUserId = createdByUserId;
    if (createdByName) body.createdByName = createdByName;
    return this.http
      .post<any>(`${this.baseUrl}/auto-generate/${teamId}`, body)
      .pipe(map(resp => Array.isArray(resp?.data) ? resp.data : []));
  }

  updateDay(dayId: number, payload: MicrocycleDayUpdatePayload): Observable<MicrocycleDay> {
    if (isDemoMode()) return of({ microcycleDayId: dayId, microcycleId: 1, dayDate: new Date().toISOString().substring(0, 10), dayType: payload.dayType ?? 'training', mdLabel: payload.mdLabel ?? null, mdLabel2: payload.mdLabel2 ?? null, trainingSessionId: payload.trainingSessionId ?? null, notes: payload.notes ?? null });
    return this.http
      .put<any>(`${this.baseUrl}/day/${dayId}`, payload)
      .pipe(map(resp => resp?.data as MicrocycleDay));
  }

  addDay(
    microcycleId: number,
    payload: { dayDate: string; dayType?: string; notes?: string | null }
  ): Observable<MicrocycleDay> {
    if (isDemoMode()) return of({ microcycleDayId: Date.now(), microcycleId, dayDate: payload.dayDate, dayType: payload.dayType ?? 'training', mdLabel: null, mdLabel2: null, trainingSessionId: null, notes: payload.notes ?? null });
    return this.http
      .post<any>(`${this.baseUrl}/${microcycleId}/day`, payload)
      .pipe(map(resp => resp?.data as MicrocycleDay));
  }

  deleteDay(dayId: number): Observable<boolean> {
    if (isDemoMode()) return of(true);
    return this.http
      .delete<any>(`${this.baseUrl}/day/${dayId}`)
      .pipe(map(resp => !!resp?.data));
  }

  // ─── DEMO ──────────────────────────────────────────────────────────
  private iso(base: Date, offset: number): string {
    const d = new Date(base);
    d.setDate(d.getDate() + offset);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }

  /** Microciclo de la semana actual: descanso lunes, entrenos y partido el domingo. */
  private demoMicrocycle(teamId: number): Microcycle {
    const today = new Date();
    // Lunes de la semana en curso.
    const monday = new Date(today);
    const dow = (today.getDay() + 6) % 7; // 0 = lunes
    monday.setDate(today.getDate() - dow);

    const days: MicrocycleDay[] = [
      { microcycleDayId: 1, microcycleId: 1, dayDate: this.iso(monday, 0), dayType: 'rest', mdLabel: 'MD+1', mdLabel2: null, trainingSessionId: null, notes: 'Descanso / recuperación' },
      { microcycleDayId: 2, microcycleId: 1, dayDate: this.iso(monday, 1), dayType: 'training', mdLabel: 'MD-5', mdLabel2: null, trainingSessionId: null, notes: 'Fuerza + técnica' },
      { microcycleDayId: 3, microcycleId: 1, dayDate: this.iso(monday, 2), dayType: 'training', mdLabel: 'MD-4', mdLabel2: null, trainingSessionId: null, notes: 'Resistencia' },
      { microcycleDayId: 4, microcycleId: 1, dayDate: this.iso(monday, 3), dayType: 'training', mdLabel: 'MD-3', mdLabel2: null, trainingSessionId: null, notes: 'Táctico' },
      { microcycleDayId: 5, microcycleId: 1, dayDate: this.iso(monday, 4), dayType: 'training', mdLabel: 'MD-2', mdLabel2: null, trainingSessionId: null, notes: 'Velocidad' },
      { microcycleDayId: 6, microcycleId: 1, dayDate: this.iso(monday, 5), dayType: 'training', mdLabel: 'MD-1', mdLabel2: null, trainingSessionId: null, notes: 'Activación' },
      { microcycleDayId: 7, microcycleId: 1, dayDate: this.iso(monday, 6), dayType: 'match', mdLabel: 'MD', mdLabel2: null, trainingSessionId: null, notes: 'Jornada de liga' },
    ];
    return {
      microcycleId: 1,
      teamId,
      clubId: 9001,
      name: 'Microciclo semana actual',
      matchDate: this.iso(monday, 6),
      matchPreparationId: null,
      startDate: this.iso(monday, 0),
      endDate: this.iso(monday, 6),
      restDay: this.iso(monday, 0),
      autoGenerated: true,
      createdByName: 'Cuerpo técnico',
      matchType: 'Liga',
      matchVenue: 'Local',
      days
    };
  }
}
